integrate-ident can handle state maps instead of only atoms
untangled-web/client pull request #58
Opened 2017-02-22 02:32 UTC by barisa

2017-02-22 03:12 UTC, awkay commented on spec/untangled/client/core_spec.cljs
> +    (behavior "Can append to an existing vector"
In untangled-spec you can actually do this more simply:
```
(assertions
    string
    expr => expr
    ...
    string
    expr => expr
   ...)
```

In other words, the acceptable syntax for assertions body is:

`(string? triple+)+`

2017-02-22 03:15 UTC, awkay commented on src/untangled/client/core.cljc
> +  [state ident & named-parameters]
Since this is a private function, you could have taken the instructions as a sequence instead of varargs. Then you would not need apply later.

2017-02-22 03:18 UTC, awkay commented
Nice addition. If you'd clean it up just a little according to the comments in the PR I've left, I'll be glad to merge it.

2017-02-22 03:23 UTC, barisa commented
I'll adapt the code to according to your comments.

2017-02-22 13:53 UTC, barisa commented
The changes were implemented. I'm not sure if the spec-test simplification is what you expected.

2017-02-23 21:02 UTC, awkay requested changes

2017-02-23 21:02 UTC, awkay commented on src/untangled/client/core.cljc
> +                           (if is-state-atom?
I'm sorry, I didn't notice this the first time. The `generic` version should just work on the map. In fact, it could be called `integrate-ident`. Then `integrate-ident!` would just be that combined with a `swap!`. That would eliminate all of this `is-atom?` logic in the middle of the algorithm.

I got distracted by the apply and didn't notice this internal detail :)

2017-02-25 21:47 UTC, awkay commented on src/untangled/client/core.cljc
> +                           (if is-state-atom?
I'm going to go ahead and make this change so you can see what I mean.

2017-02-25 22:05 UTC, merged

2017-02-25 22:06 UTC, awkay commented
So, feel free to take a look at the changes I made. They were minor, but eliminated the need for extra if/else logic around atoms, and the need for an additional function.

2017-02-28 11:40 UTC, barisa commented
I was busy in the last couple days and didn't had the time to work on this.
I wanted to do the changes now, but you already did.
Thank you @awkay for doing the changes.